# Generated by Django 3.0 on 2020-10-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='testing_image/')),
            ],
        ),
    ]
